# Create a program that will play the 'cows and bulls' game with the user. The game works
# like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every
# digit that the user guessed correctly in the correct place, they have a 'cow'. For
# every digit the user guessed correctly in the wrong place is a 'bull.' Every time the
# user makes a guess, tell them how many 'cows' and 'bulls' they have. Once the user
# guesses the correct number, the game is over. Keep track of the number of guesses the
# user makes throughout the game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like
# this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull

# Until the user guesses the number.
import random
random_number = str(random.randint(1000,9999)) #random 4 digit number
game = 1
Guesses = 0
Cows = 0
while game == 1 and Cows < 4:
    Answer = input("Guess a 4-digit number or type exit to leave: ")
    Guesses = Guesses + 1
    random_list = []
    userguess_list = []
    Cows = 0
    Bulls = 0
    for int in Answer:
        userguess_list.append(int)
    if Answer == str("exit") or Cows == 4:
        game = game - 1
    for int in random_number:
        random_list.append(int)
    Guesses = Guesses + 1
    if game == 1:
        for int in range(0,4):
            if userguess_list[int] == random_list[int]:
                Cows = Cows + 1
                userguess_list[int] = ("%")
                random_list[int] = ("*")
        for int in userguess_list:
            counter = 0
            for int2 in random_list:
                if int == int2:
                    Bulls= Bulls + 1
                    random_list[counter] = "*"
                    break
    print ("You have " + str(Cows) + " cows and " + str(Bulls) + " bulls.")
        #Answer = input("Guess a 4-digit number or type exit to leave: ")
        #Guesses = Guesses + 1
    if game ==1 and Cows < 4:
        print ("Try again!")
if Cows == 4:
    print ("You win!")

